services:
  sting-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    network_mode: "host"
    environment:
      - STING_DB_HOST=127.0.0.1
      - STING_DB_PORT=5432
      - STING_DB_NAME=sting
      - STING_DB_USER=sting
      - STING_DB_PASSWORD=sting123
